# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'o0th/tmux-nova'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
# set -g @plugin '2kabhishek/tmux2k'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'sainnhe/tmux-fzf'

# Options to make tmux more pleasant
set -g mouse on
set -g mode-keys vi
set -g default-terminal "tmux-256color"
set -g status-position top
set -g renumber-windows on
set -g status-interval 1

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 10000 lines
set -g history-limit 10000

# new windows/splits open in current pane's directory
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Reload config with prefix + r
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# fix: v should select, not rectangle-toggle
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# tmux2k settings
# set -g @tmux2k-icons-only true
# set -g @tmux2k-bg-main '#0D0D0C'

# Battery level
set -g @batt_icon_charge_tier8 ''
set -g @batt_icon_charge_tier7 ''
set -g @batt_icon_charge_tier6 ''
set -g @batt_icon_charge_tier5 ''
set -g @batt_icon_charge_tier4 ''
set -g @batt_icon_charge_tier3 ''
set -g @batt_icon_charge_tier2 ''
set -g @batt_icon_charge_tier1 ''

# Battery status
set -g @batt_icon_status_charging ''
set -g @batt_icon_status_charged ''
set -g @batt_icon_status_discharging ''
set -g @batt_icon_status_unknown ''

# tmux-nova settings
set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 

set -g @nova-pane-active-border-style "#78a9ff"
set -g @nova-pane-border-style "#282828"
set -g @nova-status-style-bg "#282828"
set -g @nova-status-style-fg "#dfdfe0"
set -g @nova-status-style-active-bg "#78a9ff"
set -g @nova-status-style-active-fg "#161616"
set -g @nova-status-style-double-bg "#161616"

set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

# Client prefix indicator
set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
set -g @nova-segment-mode-colors "#{?client_prefix,#ee5396,#be95ff} #161616"

# CPU
set -g @nova-segment-cpu "#{cpu_icon} #{cpu_percentage}"
set -g @nova-segment-cpu-colors "#282828 #33b1ff"

# RAM
set -g @nova-segment-ram "#{ram_icon} #{ram_percentage}"
set -g @nova-segment-ram-colors "#282828 #be95ff"

# Battery
set -g @nova-segment-battery "#{battery_icon} #{battery_percentage}"
set -g @nova-segment-battery-colors "#33b1ff #161616"

set -g @nova-rows 0
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "cpu ram battery"

# vim-tmux-navigator settings
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g message-style "bg=#78a9ff,fg=#161616,fill=#78a9ff"
set -g message-command-style "bg=#be95ff,fg=#161616,fill=#be95ff"
